### ISSUE TITLE
Search doesn't work well

### ISSUE THREAD

**Issue by nmtien** [sematext/docs#20]
Otis found that search on sematext.com/docs doesn't work well. For example if we search for "reference"
from sematext.com/docs it return 0 results
https://image.prntscr.com/image/DT6vD6s_RdCcvTZ_sh-JkA.png

But when i search locally it results 12 results
https://image.prntscr.com/image/Vt6pl5znRmebd3t2-v_PNA.png

There are something difference between deploy version and dev version.

**Comment by hakman** [comment]
@nmtien not exactly sure what I can / should do here.

**Comment by otisg** [comment]
@hakman Tien is assuming there is some issue with how we publish data or what's in prod or something like that.

**Comment by hakman** [comment]
I upgraded the modernizer packages and deps:
sudo pip install -U mkdocs mkdocs-material

This fixed search from what I see, but introduced some more .js and .css with unique names different than the generated ones. Not sure exactly what the problem is with those. @nmtien any ideas here? We need a solution before redeployment.

**Comment by nmtien** [comment]
Is that file application.js and application.css is missing?
Please update the suffix in custom_theme/base.html
<script src="{{ base_url }}/assets/javascripts/application-c35428f87f.js"></script>

<link rel="stylesheet" href="{{ base_url }}/assets/stylesheets/application-769c285a91.css">

Maybe different version use different suffix

**Comment by megastef** [comment]
Please check 

https://github.com/sematext/docs/blob/master/deploy.sh#L3  
https://github.com/sematext/docs/blob/master/custom_theme/base.html#L174

For application-xxxx.js I've removed the suffix and the deploy script renames the file. We might need the same procedure for other files like aplication-XXX.css. 

The problem is that we get sometimes a different suffix on different machines (probably related to different version of mkdocs and themes). The problematic part is having static suffix in our customized theme, which does not get updated when we generated the docs. 

I'm all ears to find a better solution - e.g. making sure we use the same theme and mkdocs version on development machine and our web server.

**Comment by hakman** [comment]
These are the versions of the components we have on www:

ubuntu@www:~/docs$ pip list
apt-xapian-index (0.45)
argparse (1.2.1)
backports-abc (0.5)
backports.ssl-match-hostname (3.5.0.1)
boto (2.46.1)
certifi (2017.7.27.1)
chardet (2.0.1)
Cheetah (2.4.4)
click (6.7)
cloud-init (0.7.5)
colorama (0.2.5)
configobj (4.7.2)
html5lib (0.999)
Jinja2 (2.9.6)
jsonpatch (1.3)
jsonpointer (1.0)
Landscape-Client (14.12)
livereload (2.5.1)
Markdown (2.6.9)
MarkupSafe (1.0)
mkdocs (0.16.3)
mkdocs-material (1.10.1)
oauth (1.0.1)
PAM (0.4.2)
pip (1.5.4)
prettytable (0.7.2)
pycurl (7.19.3)
Pygments (2.2.0)
pyinotify (0.9.4)
pymdown-extensions (4.0)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5ubuntu2)
python-debian (0.1.21-nmu2ubuntu2)
PyYAML (3.10)
requests (2.2.1)
setuptools (3.3)
singledispatch (3.4.0.3)
six (1.5.2)
ssh-import-id (3.21)
tornado (4.5.1)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
urllib3 (1.7.1)
wheel (0.24.0)
wsgiref (0.1.2)
zope.interface (4.0.5)
ubuntu@www:~/docs$

**Comment by hakman** [comment]
I think search works ok now.
